# Generated by Django 3.2.6 on 2021-08-22 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shirt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shirt_name', models.CharField(max_length=30)),
                ('shirt_price', models.IntegerField()),
                ('shirt_description', models.CharField(max_length=50)),
                ('shirt_img', models.ImageField(upload_to='images')),
            ],
            options={
                'db_table': 'shirt',
            },
        ),
    ]
